---
title: "Initial Korean covid 19"
author: "Rita Jarbanda"
date: "Fall 2023"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?

## Methods

Based on the data we found in KRdata, we will try and find out if there is a difference between men and women. Is there any difference in how covid kills men and women. Is covid more harmful to men? Or is it more harmful to women?
We are going to use the CandP helper files to compare two categorical data types Sex and Results Because this is a cat-cat problem we will first create a bar chart, then we will run favstates to show graphical and numerical results.
For inferential results we are going to run a Chi-Squared test which will tell us if there is a difference in the data but not where. 

## Graphical results - use ggplot commands to do this  



  





  
## Numerical results


## Inferential results 




## Conclusions

